apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlepay:8fa88a9b108be70ea6ef28715e02e5c4733c9087
        ports:
        - containerPort: 80
